name: Generate Metrics

on:
  schedule:
    - cron: '30 2 * * *' # 02:30 UTC daily
  workflow_dispatch: {}

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          user: ruskicoder
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Commit metrics
        run: |
          # Safely handle first run when metrics.svg does not yet exist
          if [ ! -f metrics.svg ]; then
            echo "metrics.svg not found after generation step. Listing repo root for diagnostics:";
            ls -al
            echo "No metrics.svg to commit (possibly generation failed).";
            exit 0
          fi

          # Use -- to separate path to avoid ambiguity
          if git diff --quiet -- metrics.svg; then
            echo "No changes in metrics.svg"
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add metrics.svg
            git commit -m 'chore(metrics): update metrics.svg'
            git push
          fi
