name: Update Featured Projects

on:
  schedule:
    - cron: '15 1 * * *' # 01:15 UTC daily
  workflow_dispatch: {}

jobs:
  featured:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update featured projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node assets/js/update-featured.js

      - name: Commit changes
        run: |
          if git diff --quiet README.md; then
            echo "No featured project changes.";
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m 'chore(featured): update featured projects'
            git push
          fi
